<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'order' => [[], ['_controller' => 'App\\Controller\\OrderController::index'], [], [['text', '/order']], [], []],
    'product' => [[], ['_controller' => 'App\\Controller\\ProductController::index'], [], [['text', '/product']], [], []],
    'api_endpointcreateUser' => [[], ['_controller' => 'App\\Controller\\UserController::create'], [], [['text', '/api/register']], [], []],
    'api_endpointloginUser' => [[], ['_controller' => 'App\\Controller\\UserController::login'], [], [['text', '/api/login']], [], []],
    'api_endpointshowUser' => [['id'], ['_controller' => 'App\\Controller\\UserController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/user']], [], []],
    'api_endpointupdateUser' => [['id'], ['_controller' => 'App\\Controller\\UserController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/user']], [], []],
];
